answer = [
'''Variable can be a integer or a string in a program. <STOP>''',
'''In programming, a structure that holds data and is uniquely named by the programmer. <STOP> It holds the data assigned to it until a new value is assigned or the program is finished. <STOP>''',
'''A variable is a location in memory where a value can be stored. <STOP>''',
'''Variable is a location in the computer 's memory, in which a value can be stored and later can retrieve that value. <STOP>''',
'''A variable is a location in the computer 's memory where a value can be stored for use by a program. <STOP> Each variable has a name, a value, a type and a size. <STOP>''',
'''A named object that can hold a numerical or letter value <STOP>''',
'''It is a sybol or name for a value or number. <STOP> Example: "a used number" can stand for any given number, and the programmer can refer to that number by using the variable name. <STOP>''',
'''A variable is a location in the computers memory where a value can be stored for use by a program <STOP>''',
'''An identifier that holds a location in memory. <STOP>''',
'''a block of memory that holds a specific type of data <STOP>''',
'''It is a location in the computer 's memory where it can be stored for use by a program. <STOP>''',
'''A location in memory where value can be stored. <STOP>''',
'''a value or word that can assume any of a set of values <STOP>''',
'''A pointer to a location in memory. <STOP>''',
'''A variable is the memory address for a specific type of stored data, or from a mathematical perspective, a symbol representing a fixed definition with changing values. <STOP>''',
'''A variable is a value that is subject to change in a computer 's memory that can be used by programs. <STOP> Programs can change the value of the variable and recall it later or act on it directly. <STOP>''',
'''a symbol that stands in for a value that may or may not change depending on the program. <STOP>''',
'''a placeholder to hold information used in the program ... for example: int can hold: 1, 2, 3, 4, 68, 72, 256, etc. float can hold: 1.54, 55.55, 1.24, 5.657, 8.8123, et. char can hold: A, B, C, D, E, F,!, 4, 5, 6, P, etc. <STOP>''',
'''a stored value used by the program <STOP>''',
'''A way to store different values into the program, such as numbers, words, letters, etc. <STOP>''',
'''An object with a location in memory where value can be stored <STOP>''',
'''location in memory where a value can be stored <STOP>''',
'''a variable is an object where data is stored. <STOP>''',
'''Location in memory where a value can be stored. <STOP>''',
'''it is a location in memory where value can be stored <STOP>''',
'''A variable is the location in a computer 's memory where a value can be stored for use by a program. <STOP>''',
'''A variable is a location in a computers memory where a value can be stored for use by a program. <STOP>''',
'''a location in memory where data can be stored and retrieved <STOP>''',
'''Is a method or identifier I would say, we use to bind a data object to memory location; which is then stored in a location that can be accessed when and manipulated later when the variable name is called. <STOP>''',
]

ave = [
2,
4.5,
5,
5,
5,
3.5,
4,
5,
4,
5,
5,
5,
3,
4,
5,
5,
4,
4.5,
4.5,
4.5,
3.5,
5,
3.5,
5,
5,
5,
5,
5,
5,
]

me = [
1,
4,
5,
5,
5,
2,
3,
5,
3,
5,
5,
5,
3,
3,
5,
5,
3,
4,
4,
4,
2,
5,
2,
5,
5,
5,
5,
5,
5,
]

other = [
3,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
3,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
]

question = '''What is a variable?'''

gt = '''A location in memory that can store a value.'''